//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaumRoll40.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fav
    {
        public int PostId { get; set; }
        public int UserId { get; set; }
    }
}
